### ISSUE TITLE
Multiple line string how achive with maven

### ISSUE THREAD

**Issue by oldbig** [11039850/monalisa-orm#2]
thanks for your good job,  concat string torture me alot before.
there is eclipse plugin, but how compile it with maven? is there some way to make maven also can compile that multiple line String?

**Comment by 11039850** [comment]
Eclipse plugin is just a smokescreen, the actual java code is still a lot of escape line.

You can open the source file with Notepad to see how it is going on.

So, do not need to do anything, you can directly use the maven.

[references](https://github.com/11039850/monalisa-orm/wiki/Multiple-line%20syntax#references)

**Comment by oldbig** [comment]
> open the source file with Notepad to see how it is going on

aha, I see, so good， the source code is changed.
impressive :+1:
