### ISSUE TITLE
good project

### ISSUE THREAD

**Issue by lishoujun** [11039850/monalisa-orm#3]

**Comment by roinlym** [comment]
public List  selectUserBlogs(int user_id){ 
        Query q=TestDB.DB.createQuery();
        q.add(""/**~{
                SELECT a.id,a.name,b.title, b.content,b.create_time
                    FROM user a, blog b   
                    WHERE a.id=b.user_id AND a.id=?
        }*/, user_id);
        return q.getList(); 
    }
保存后没有输出SQL，也没有生成对应的类，只输出了这个
2016-11-02 16:15:18 [I] $VERSION$ update to: 24

**Comment by 11039850** [comment]
```java
import com.tsc9526.monalisa.orm.annotation.Select;
...
@Select   
public List  selectUserBlogs(int user_id){ 
  ...
}
```
