### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by whoevelmanns** [11039850/monalisa-orm#4]
Hi there,
This is a very useful orm.
I´m developing programms in conjunction with oracle and therefor I think it would be fine if I could change the placeholder mark from $ to &.
Perhaps you could give me an setting part in the Preferences?
Regards
Werner

**Comment by 11039850** [comment]
Multi-string plugin source code is here:
https://github.com/11039850/monalisa-eclipse

You should modify source file:
   src/com/tsc9526/monalisa/plugin/eclipse/editors/LinesCodeTransform.java

change 
`public final static char varChar    = '$';`
to
`public final static char varChar    = '&';`

and rebuild this plugin.

OR  download from here(customized specifically for you): 
[https://github.com/11039850/monalisa-eclipse/zip/com.tsc9526.monalisa.plugin.eclipse_2.0.0_var-&.jar](https://github.com/11039850/monalisa-eclipse/blob/master/zip/com.tsc9526.monalisa.plugin.eclipse_2.0.0_var-&.jar?raw=true)
Uninstall the previous monalisa plugin and put this jar to your eclipse plugin directory.

**Comment by Oberdepp** [comment]
Thank you very mich. 
This is a great help.

Sent by Mailwise – Your emails, with style.:)


-------- Originalnachricht --------
Betreff: Re: [11039850/monalisa-orm] Feature request (#4)
Von: zzg <notifications@github.com>
An: 11039850/monalisa-orm <monalisa-orm@noreply.github.com>
Cc: Oberdepp <info@whwk.de>,Author <author@noreply.github.com>
